extraction:
  cpp:
    after_prepare: 
      - python report.py 82
  cobol:
    after_prepare: 
      - python report.py 82
  csharp:
    after_prepare: 
      - python report.py 82
  java:
    after_prepare: 
      - python report.py 82
  javascript:
    after_prepare: 
      - python report.py 82
  python:
    after_prepare: 
      - python report.py 82
